// src/stores/homophonesStore.ts
import { writable } from 'svelte/store';

interface Homophones {
  [key: string]: string[];
}

const homophonesData: Homophones = {
    "Abel": ["able"],
    "able": ["Abel"],
    "accede": ["exceed"],
    "exceed": ["accede"],
    "accept": ["except"],
    "except": ["accept"],
    "acclamation": ["acclimation"],
    "acclimation": ["acclamation"],
    "acts": ["ax"],
    "ax": ["acts"],
    "ad": ["add"],
    "add": ["ad"],
    "Adam": ["atom"],
    "atom": ["Adam"],
    "addition": ["edition"],
    "edition": ["addition"],
    "adds": ["adz", "ads"],
    "adz": ["adds", "ads"],
    "ads": ["adds", "adz"],
    "adduce": ["educe"],
    "educe": ["adduce"],
    "adherence": ["adherents"],
    "adherents": ["adherence"],
    "adieu": ["ado"],
    "ado": ["adieu"],
    "aerial": ["ariel"],
    "ariel": ["aerial"],
    "affect": ["effect"],
    "effect": ["affect"],
    "affected": ["effected"],
    "effected": ["affected"],
    "affects": ["effects"],
    "effects": ["affects"],
    "afterward": ["afterword"],
    "afterword": ["afterward"],
    "aid": ["aide"],
    "aide": ["aid"],
    "ail": ["ale"],
    "ale": ["ail"],
    "air": ["heir", "err"],
    "heir": ["air", "err"],
    "err": ["air", "heir"],
    "aisle": ["isle", "I’ll"],
    "isle": ["aisle", "I’ll"],
    "I’ll": ["aisle", "isle"],
    "all ready": ["already"],
    "already": ["all ready"],
    "all together": ["altogether"],
    "altogether": ["all together"],
    "all ways": ["always"],
    "always": ["all ways"],
    "all": ["awl"],
    "awl": ["all"],
    "allowed": ["aloud"],
    "aloud": ["allowed"],
    "allude": ["elude"],
    "elude": ["allude"],
    "alluded": ["eluded"],
    "eluded": ["alluded"],
    "allusion": ["illusion"],
    "illusion": ["allusion"],
    "allusive": ["elusive", "illusive"],
    "elusive": ["allusive", "illusive"],
    "illusive": ["allusive", "elusive"],
    "altar": ["alter"],
    "alter": ["altar"],
    "amend": ["emend"],
    "emend": ["amend"],
    "analyst": ["annalist"],
    "annalist": ["analyst"],
    "ant": ["aunt"],
    "aunt": ["ant"],
    "apatite": ["appetite"],
    "appetite": ["apatite"],
    "apprise": ["apprize"],
    "apprize": ["apprise"],
    "arc": ["ark"],
    "ark": ["arc"],
    "arrant": ["errant"],
    "errant": ["arrant"],
    "ascent": ["assent"],
    "assent": ["ascent"],
    "assistance": ["assistants"],
    "assistants": ["assistance"],
    "ate": ["eight"],
    "eight": ["ate"],
    "auger": ["augur"],
    "augur": ["auger"],
    "aural": ["oral"],
    "oral": ["aural"],
    "aureole": ["oriole"],
    "oriole": ["aureole"],
    "away": ["aweigh"],
    "aweigh": ["away"],
    "axel": ["axle"],
    "axle": ["axel"],
    "axes": ["axis"],
    "axis": ["axes"],
    "aye": ["eye", "I"],
    "eye": ["aye", "I"],
    "I": ["aye", "eye"],
    "ayes": ["eyes"],
    "eyes": ["ayes"],
    "baa": ["bah"],
    "bah": ["baa"],
    "baal": ["bail", "bale"],
    "bail": ["baal", "bale"],
    "bale": ["baal", "bail"],
    "babble": ["Babel"],
    "Babel": ["babble"],
    "bad": ["bade"],
    "bade": ["bad"],
    "bait": ["bate"],
    "bate": ["bait"],
    "baited": ["bated"],
    "bated": ["baited"],
    "bald": ["balled", "bawled"],
    "balled": ["bald", "bawled"],
    "bawled": ["bald", "balled"],
    "balm": ["bomb", "bombe"],
    "bomb": ["balm", "bombe"],
    "bombe": ["balm", "bomb"],
    "band": ["banned"],
    "banned": ["band"],
    "bard": ["barred"],
    "barred": ["bard"],
    "bare": ["bear"],
    "bear": ["bare"],
    "baron": ["barren"],
    "barren": ["baron"],
    "basal": ["basil"],
    "basil": ["basal"],
    "base": ["bass"],
    "bass": ["base"],
    "based": ["baste"],
    "baste": ["based"],
    "bases": ["basis"],
    "basis": ["bases"],
    "bask": ["basque"],
    "basque": ["bask"],
    "be": ["bee"],
    "bee": ["be"],
    "beach": ["beech"],
    "beech": ["beach"],
    "beat": ["beet"],
    "beet": ["beat"],
    "beau": ["bow"],
    "bow": ["beau"],
    "been": ["bin"],
    "bin": ["been"],
    "beer": ["bier"],
    "bier": ["beer"],
    "bell": ["belle"],
    "belle": ["bell"],
    "berry": ["bury"],
    "bury": ["berry"],
    "berth": ["birth"],
    "birth": ["berth"],
    "better": ["bettor"],
    "bettor": ["better"],
    "bib": ["bibb"],
    "bibb": ["bib"],
    "bight": ["bite", "byte"],
    "bite": ["bight", "byte"],
    "byte": ["bight", "bite"],
    "billed": ["build"],
    "build": ["billed"],
    "bird": ["burred"],
    "burred": ["bird"],
    "bloc": ["block"],
    "block": ["bloc"],
    "blue": ["blew"],
    "blew": ["blue"],
    "boar": ["bore"],
    "bore": ["boar"],
    "board": ["bored"],
    "bored": ["board"],
    "boarder": ["border"],
    "border": ["boarder"],
    "bode": ["bowed"],
    "bowed": ["bode"],
    "bold": ["bowled"],
    "bowled": ["bold"],
    "bolder": ["boulder"],
    "boulder": ["bolder"],
    "bootie": ["booty"],
    "booty": ["bootie"],
    "born": ["borne"],
    "borne": ["born"],
    "borough": ["burro", "burrow"],
    "burro": ["borough", "burrow"],
    "burrow": ["borough", "burro"],
    "bough": ["bow"],
    "bouillon": ["bullion"],
    "bullion": ["bouillon"],
    "boy": ["buoy"],
    "buoy": ["boy"],
    "braid": ["brayed"],
    "brayed": ["braid"],
    "braise": ["brays"],
    "brays": ["braise"],
    "brake": ["break"],
    "break": ["brake"],
    "breach": ["breech"],
    "breech": ["breach"],
    "bread": ["bred"],
    "bred": ["bread"],
    "brewed": ["brood"],
    "brood": ["brewed"],
    "brews": ["bruise"],
    "bruise": ["brews"],
    "bridal": ["bridle"],
    "bridle": ["bridal"],
    "broach": ["brooch"],
    "brooch": ["broach"],
    "brows": ["browse"],
    "browse": ["brows"],
    "brut": ["brute"],
    "brute": ["brut"],
    "bussed": ["bust"],
    "bust": ["bussed"],
    "but": ["butt"],
    "butt": ["but"],
    "buy": ["by", "bye"],
    "by": ["buy", "bye"],
    "bye": ["buy", "by"],
    "cache": ["cash"],
    "cash": ["cache"],
    "caddie": ["caddy"],
    "caddy": ["caddie"],
    "Cain": ["cane"],
    "cane": ["Cain"],
    "calendar": ["calender"],
    "calender": ["calendar"],
    "callous": ["callus"],
    "callus": ["callous"],
    "canapé": ["canopy"],
    "canopy": ["canapé"],
    "cannon": ["canon"],
    "canon": ["cannon"],
    "canter": ["cantor"],
    "cantor": ["canter"],
    "canvas": ["canvass"],
    "canvass": ["canvas"],
    "capital": ["capitol"],
    "capitol": ["capital"],
    "carat": ["carrot", "caret", "karat"],
    "carrot": ["carat", "caret", "karat"],
    "caret": ["carat", "carrot", "karat"],
    "karat": ["carat", "carrot", "caret"],
    "carol": ["carrel"],
    "carrel": ["carol"],
    "cast": ["caste"],
    "caste": ["cast"],
    "caster": ["castor"],
    "castor": ["caster"],
    "cause": ["caws"],
    "caws": ["cause"],
    "cedar": ["seeder"],
    "seeder": ["cedar"],
    "cede": ["seed"],
    "seed": ["cede"],
    "ceiling": ["sealing"],
    "sealing": ["ceiling"],
    "cell": ["sell"],
    "sell": ["cell"],
    "cellar": ["seller"],
    "seller": ["cellar"],
    "censor": ["sensor"],
    "sensor": ["censor"],
    "cent": ["scent", "sent"],
    "scent": ["cent", "sent"],
    "sent": ["cent", "scent"],
    "cents": ["scents", "sense"],
    "scents": ["cents", "sense"],
    "sense": ["cents", "scents"],
    "cereal": ["serial"],
    "serial": ["cereal"],
    "Ceres": ["series"],
    "series": ["Ceres"],
    "cession": ["session"],
    "session": ["cession"],
    "chance": ["chants"],
    "chants": ["chance"],
    "chased": ["chaste"],
    "chaste": ["chased"],
    "chauffeur": ["shofar"],
    "shofar": ["chauffeur"],
    "cheap": ["cheep"],
    "cheep": ["cheap"],
    "check": ["Czech"],
    "Czech": ["check"],
    "chews": ["choose"],
    "choose": ["chews"],
    "chic": ["sheik"],
    "sheik": ["chic"],
    "Chile": ["chilly", "chili"],
    "chilly": ["Chile", "chili"],
    "chili": ["Chile", "chilly"],
    "choir": ["quire"],
    "quire": ["choir"],
    "choral": ["coral"],
    "coral": ["choral"],
    "chord": ["cord", "cored"],
    "cord": ["chord", "cored"],
    "cored": ["chord", "cord"],
    "chute": ["shoot"],
    "shoot": ["chute"],
    "cite": ["sight", "site"],
    "sight": ["cite", "site"],
    "site": ["cite", "sight"],
    "cited": ["sided", "sighted"],
    "sided": ["cited", "sighted"],
    "sighted": ["cited", "sided"],
    "clack": ["claque"],
    "claque": ["clack"],
    "clamber": ["clammer", "clamor"],
    "clammer": ["clamber", "clamor"],
    "clamor": ["clamber", "clammer"],
    "clause": ["claws"],
    "claws": ["clause"],
    "clew": ["clue"],
    "clue": ["clew"],
    "click": ["clique"],
    "clique": ["click"],
    "climb": ["clime"],
    "clime": ["climb"],
    "close": ["clothes", "cloze"],
    "clothes": ["close", "cloze"],
    "cloze": ["close", "clothes"],
    "coal": ["cole"],
    "cole": ["coal"],
    "coarse": ["course"],
    "course": ["coarse"],
    "coarser": ["courser"],
    "courser": ["coarser"],
    "coat": ["cote"],
    "cote": ["coat"],
    "coax": ["cokes"],
    "cokes": ["coax"],
    "coffers": ["coughers"],
    "coughers": ["coffers"],
    "collard": ["collared"],
    "collared": ["collard"],
    "colonel": ["kernel"],
    "kernel": ["colonel"],
    "complacent": ["complaisant"],
    "complaisant": ["complacent"],
    "complement": ["compliment"],
    "compliment": ["complement"],
    "complementary": ["complimentary"],
    "complimentary": ["complementary"],
    "conceded": ["conceited"],
    "conceited": ["conceded"],
    "confirmation": ["conformation"],
    "conformation": ["confirmation"],
    "consonance": ["consonants"],
    "consonants": ["consonance"],
    "continence": ["continents"],
    "continents": ["continence"],
    "coo": ["coup"],
    "coup": ["coo"],
    "coolie": ["coulee"],
    "coulee": ["coolie"],
    "coop": ["coupe"],
    "coupe": ["coop"],
    "cops": ["copse"],
    "copse": ["cops"],
    "core": ["corps"],
    "corps": ["core"],
    "correspondence": ["correspondents"],
    "correspondents": ["correspondence"],
    "cousin": ["cozen"],
    "cozen": ["cousin"],
    "coward": ["cowered"],
    "cowered": ["coward"],
    "coy": ["koi"],
    "koi": ["coy"],
    "craft": ["kraft"],
    "kraft": ["craft"],
    "crape": ["crepe"],
    "crepe": ["crape"],
    "crawl": ["kraal"],
    "kraal": ["crawl"],
    "creak": ["creek"],
    "creek": ["creak"],
    "crewel": ["cruel"],
    "cruel": ["crewel"],
    "crews": ["cruise"],
    "cruise": ["crews"],
    "cue": ["queue"],
    "queue": ["cue"],
    "currant": ["current"],
    "current": ["currant"],
    "curser": ["cursor"],
    "cursor": ["curser"],
    "cygnet": ["signet"],
    "signet": ["cygnet"],
    "cymbal": ["symbol"],
    "symbol": ["cymbal"],
    "cypress": ["Cyprus"],
    "Cyprus": ["cypress"],
    "dam": ["damn"],
    "damn": ["dam"],
    "Dane": ["deign"],
    "deign": ["Dane"],
    "days": ["daze"],
    "daze": ["days"],
    "dear": ["deer"],
    "deer": ["dear"],
    "defused": ["diffused"],
    "diffused": ["defused"],
    "dense": ["dents"],
    "dents": ["dense"],
    "descent": ["dissent"],
    "dissent": ["descent"],
    "desert": ["dessert"],
    "dessert": ["desert"],
    "dew": ["do", "due"],
    "do": ["dew", "due"],
    "due": ["dew", "do"],
    "die": ["dye"],
    "dye": ["die"],
    "disburse": ["disperse"],
    "disperse": ["disburse"],
    "discreet": ["discrete"],
    "discrete": ["discreet"],
    "doc": ["dock"],
    "dock": ["doc"],
    "does": ["doze"],
    "doze": ["does"],
    "done": ["dun"],
    "dun": ["done"],
    "draft": ["draught"],
    "draught": ["draft"],
    "dual": ["duel"],
    "duel": ["dual"],
    "ducked": ["duct"],
    "duct": ["ducked"],
    "ducks": ["ducts"],
    "ducts": ["ducks"],
    "dyeing": ["dying"],
    "dying": ["dyeing"],
    "earn": ["urn"],
    "urn": ["earn"],
    "eave": ["eve"],
    "eve": ["eave"],
    "eek": ["eke"],
    "eke": ["eek"],
    "elicit": ["illicit"],
    "illicit": ["elicit"],
    "enumerable": ["innumerable"],
    "innumerable": ["enumerable"],
    "ewe": ["you", "yew"],
    "you": ["ewe", "yew"],
    "yew": ["ewe", "you"],
    "ewes": ["yews", "use"],
    "yews": ["ewes", "use"],
    "use": ["ewes", "yews"],
    "exercise": ["exorcise"],
    "exorcise": ["exercise"],
    "eyed": ["I’d"],
    "I’d": ["eyed"],
    "eyelet": ["islet"],
    "islet": ["eyelet"],
    "facts": ["fax"],
    "fax": ["facts"],
    "faint": ["feint"],
    "feint": ["faint"],
    "fair": ["fare"],
    "fare": ["fair"],
    "fairy": ["ferry"],
    "ferry": ["fairy"],
    "fate": ["fete"],
    "fete": ["fate"],
    "faun": ["fawn"],
    "fawn": ["faun"],
    "faze": ["phase"],
    "phase": ["faze"],
    "feat": ["feet"],
    "feet": ["feat"],
    "fends": ["fens"],
    "fens": ["fends"],
    "few": ["phew"],
    "phew": ["few"],
    "fiancé": ["fiancée"],
    "fiancée": ["fiancé"],
    "fill": ["Phil"],
    "Phil": ["fill"],
    "find": ["fined"],
    "fined": ["find"],
    "finish": ["Finnish"],
    "Finnish": ["finish"],
    "fir": ["fur"],
    "fur": ["fir"],
    "fisher": ["fissure"],
    "fissure": ["fisher"],
    "flair": ["flare"],
    "flare": ["flair"],
    "flea": ["flee"],
    "flee": ["flea"],
    "flew": ["flu", "flue"],
    "flu": ["flew", "flue"],
    "flue": ["flew", "flu"],
    "flier": ["flyer"],
    "flyer": ["flier"],
    "flocks": ["phlox"],
    "phlox": ["flocks"],
    "floe": ["flow"],
    "flow": ["floe"],
    "flour": ["flower"],
    "flower": ["flour"],
    "foaled": ["fold"],
    "fold": ["foaled"],
    "foe": ["faux"],
    "faux": ["foe"],
    "for": ["four", "fore"],
    "four": ["for", "fore"],
    "fore": ["for", "four"],
    "foregone": ["forgone"],
    "forgone": ["foregone"],
    "foreword": ["forward"],
    "forward": ["foreword"],
    "fort": ["forte"],
    "forte": ["fort"],
    "forth": ["fourth"],
    "fourth": ["forth"],
    "foul": ["fowl"],
    "fowl": ["foul"],
    "franc": ["frank"],
    "frank": ["franc"],
    "frays": ["phrase"],
    "phrase": ["frays"],
    "frees": ["freeze", "frieze"],
    "freeze": ["frees", "frieze"],
    "frieze": ["frees", "freeze"],
    "friar": ["fryer"],
    "fryer": ["friar"],
    "gaff": ["gaffe"],
    "gaffe": ["gaff"],
    "Gail": ["gale"],
    "gale": ["Gail"],
    "gait": ["gate"],
    "gate": ["gait"],
    "gamble": ["gambol"],
    "gambol": ["gamble"],
    "gel": ["jell"],
    "jell": ["gel"],
    "gene": ["jean"],
    "jean": ["gene"],
    "gibe": ["jibe"],
    "jibe": ["gibe"],
    "gild": ["guild"],
    "guild": ["gild"],
    "gilder": ["guilder"],
    "guilder": ["gilder"],
    "gilt": ["guilt"],
    "guilt": ["gilt"],
    "gneiss": ["nice"],
    "nice": ["gneiss"],
    "gnome": ["Nome"],
    "Nome": ["gnome"],
    "gnu": ["knew", "new"],
    "knew": ["gnu", "new"],
    "new": ["gnu", "knew"],
    "gofer": ["gopher"],
    "gopher": ["gofer"],
    "gored": ["gourd"],
    "gourd": ["gored"],
    "gorilla": ["guerilla"],
    "guerilla": ["gorilla"],
    "grade": ["grayed"],
    "grayed": ["grade"],
    "graft": ["graphed"],
    "graphed": ["graft"],
    "graham": ["gram"],
    "gram": ["graham"],
    "grate": ["great"],
    "great": ["grate"],
    "grater": ["greater"],
    "greater": ["grater"],
    "grease": ["Greece"],
    "Greece": ["grease"],
    "grill": ["grille"],
    "grille": ["grill"],
    "grisly": ["grizzly"],
    "grizzly": ["grisly"],
    "groan": ["grown"],
    "grown": ["groan"],
    "guessed": ["guest"],
    "guest": ["guessed"],
    "gym": ["Jim"],
    "Jim": ["gym"],
    "hail": ["hale"],
    "hale": ["hail"],
    "hair": ["hare"],
    "hare": ["hair"],
    "hall": ["haul"],
    "haul": ["hall"],
    "halve": ["have"],
    "have": ["halve"],
    "handmade": ["handmaid"],
    "handmaid": ["handmade"],
    "handsome": ["hansom"],
    "hansom": ["handsome"],
    "hangar": ["hanger"],
    "hanger": ["hangar"],
    "hart": ["heart"],
    "heart": ["hart"],
    "hay": ["hey"],
    "hey": ["hay"],
    "hays": ["haze"],
    "haze": ["hays"],
    "he’d": ["heed"],
    "heed": ["he’d"],
    "he’ll": ["heal", "heel"],
    "heal": ["he’ll", "heel"],
    "heel": ["he’ll", "heal"],
    "hear": ["here"],
    "here": ["hear"],
    "heard": ["herd"],
    "herd": ["heard"],
    "heroin": ["heroine"],
    "heroine": ["heroin"],
    "hertz": ["hurts"],
    "hurts": ["hertz"],
    "hew": ["hue", "Hugh"],
    "hue": ["hew", "Hugh"],
    "Hugh": ["hew", "hue"],
    "hi": ["high"],
    "high": ["hi"],
    "higher": ["hire"],
    "hire": ["higher"],
    "him": ["hymn"],
    "hymn": ["him"],
    "ho": ["hoe"],
    "hoe": ["ho"],
    "hoard": ["horde"],
    "horde": ["hoard"],
    "hoarse": ["horse"],
    "horse": ["hoarse"],
    "hoes": ["hose"],
    "hose": ["hoes"],
    "hold": ["holed"],
    "holed": ["hold"],
    "hole": ["whole"],
    "whole": ["hole"],
    "holey": ["holy", "wholly"],
    "holy": ["holey", "wholly"],
    "wholly": ["holey", "holy"],
    "hoop": ["whoop"],
    "whoop": ["hoop"],
    "hostel": ["hostile"],
    "hostile": ["hostel"],
    "hour": ["our"],
    "our": ["hour"],
    "humerus": ["humorous"],
    "humorous": ["humerus"],
    "idle": ["idol", "idyll"],
    "idol": ["idle", "idyll"],
    "idyll": ["idle", "idol"],
    "immanent": ["imminent"],
    "imminent": ["immanent"],
    "impassable": ["impassible"],
    "impassible": ["impassable"],
    "in": ["inn"],
    "inn": ["in"],
    "incite": ["insight"],
    "insight": ["incite"],
    "innocence": ["innocents"],
    "innocents": ["innocence"],
    "it’s": ["its"],
    "its": ["it’s"],
    "jam": ["jamb"],
    "jamb": ["jam"],
    "knap": ["nap"],
    "nap": ["knap"],
    "knave": ["nave"],
    "nave": ["knave"],
    "knead": ["kneed", "need"],
    "kneed": ["knead", "need"],
    "need": ["knead", "kneed"],
    "knickers": ["nickers"],
    "nickers": ["knickers"],
    "knight": ["night"],
    "night": ["knight"],
    "knit": ["nit"],
    "nit": ["knit"],
    "knock": ["nock"],
    "nock": ["knock"],
    "knot": ["not"],
    "not": ["knot"],
    "know": ["no"],
    "no": ["know"],
    "knows": ["nose"],
    "nose": ["knows"],
    "lacks": ["lax"],
    "lax": ["lacks"],
    "ladder": ["latter"],
    "latter": ["ladder"],
    "lade": ["laid"],
    "laid": ["lade"],
    "lain": ["lane"],
    "lane": ["lain"],
    "lama": ["llama"],
    "llama": ["lama"],
    "Lapps": ["laps", "lapse"],
    "laps": ["Lapps", "lapse"],
    "lapse": ["Lapps", "laps"],
    "lay": ["lei"],
    "lei": ["lay"],
    "lays": ["laze", "leis"],
    "laze": ["lays", "leis"],
    "leis": ["lays", "laze"],
    "lea": ["lee"],
    "lee": ["lea"],
    "leach": ["leech"],
    "leech": ["leach"],
    "lead": ["led"],
    "led": ["lead"],
    "leak": ["leek"],
    "leek": ["leak"],
    "lean": ["lien"],
    "lien": ["lean"],
    "leased": ["least"],
    "least": ["leased"],
    "lends": ["lens"],
    "lens": ["lends"],
    "lessen": ["lesson"],
    "lesson": ["lessen"],
    "lets": ["let’s"],
    "let’s": ["lets"],
    "levee": ["levy"],
    "levy": ["levee"],
    "liar": ["lier", "lyre"],
    "lier": ["liar", "lyre"],
    "lyre": ["liar", "lier"],
    "lichen": ["liken"],
    "liken": ["lichen"],
    "lie": ["lye"],
    "lye": ["lie"],
    "lieu": ["Lou"],
    "Lou": ["lieu"],
    "links": ["lynx"],
    "lynx": ["links"],
    "literal": ["littoral"],
    "littoral": ["literal"],
    "lo": ["low"],
    "low": ["lo"],
    "load": ["lode", "lowed"],
    "lode": ["load", "lowed"],
    "lowed": ["load", "lode"],
    "loan": ["lone"],
    "lone": ["loan"],
    "loath": ["loathe"],
    "loathe": ["loath"],
    "loch": ["lock"],
    "lock": ["loch"],
    "lochs": ["locks", "lox"],
    "locks": ["lochs", "lox"],
    "lox": ["lochs", "locks"],
    "loot": ["lute"],
    "lute": ["loot"],
    "lumbar": ["lumber"],
    "lumber": ["lumbar"],
    "madder": ["matter"],
    "matter": ["madder"],
    "made": ["maid"],
    "maid": ["made"],
    "mail": ["male"],
    "male": ["mail"],
    "main": ["mane", "Maine"],
    "mane": ["main", "Maine"],
    "Maine": ["main", "mane"],
    "maize": ["maze"],
    "maze": ["maize"],
    "mall": ["maul"],
    "maul": ["mall"],
    "manner": ["manor"],
    "manor": ["manner"],
    "mantel": ["mantle"],
    "mantle": ["mantel"],
    "marc": ["mark"],
    "mark": ["marc"],
    "mare": ["mayor"],
    "mayor": ["mare"],
    "marry": ["merry", "Mary"],
    "merry": ["marry", "Mary"],
    "Mary": ["marry", "merry"],
    "marshal": ["martial"],
    "martial": ["marshal"],
    "marten": ["martin"],
    "martin": ["marten"],
    "massed": ["mast"],
    "mast": ["massed"],
    "mat": ["matte"],
    "matte": ["mat"],
    "may be": ["maybe"],
    "maybe": ["may be"],
    "mean": ["mien"],
    "mien": ["mean"],
    "meat": ["meet", "mete"],
    "meet": ["meat", "mete"],
    "mete": ["meat", "meet"],
    "meatier": ["meteor"],
    "meteor": ["meatier"],
    "medal": ["metal", "mettle", "meddle"],
    "metal": ["medal", "mettle", "meddle"],
    "mettle": ["medal", "metal", "meddle"],
    "meddle": ["medal", "metal", "mettle"],
    "mewl": ["mule"],
    "mule": ["mewl"],
    "mews": ["muse"],
    "muse": ["mews"],
    "might": ["mite"],
    "mite": ["might"],
    "mil": ["mill"],
    "mill": ["mil"],
    "mince": ["mints"],
    "mints": ["mince"],
    "mind": ["mined"],
    "mined": ["mind"],
    "miner": ["minor"],
    "minor": ["miner"],
    "missal": ["missile"],
    "missile": ["missal"],
    "missed": ["mist"],
    "mist": ["missed"],
    "misses": ["Mrs."],
    "Mrs.": ["misses"],
    "moan": ["mown"],
    "mown": ["moan"],
    "moat": ["mote"],
    "mote": ["moat"],
    "mode": ["mowed"],
    "mowed": ["mode"],
    "mood": ["mooed"],
    "mooed": ["mood"],
    "moose": ["mousse"],
    "mousse": ["moose"],
    "morn": ["mourn"],
    "mourn": ["morn"],
    "morning": ["mourning"],
    "mourning": ["morning"],
    "mucous": ["mucus"],
    "mucus": ["mucous"],
    "muscle": ["mussel"],
    "mussel": ["muscle"],
    "mussed": ["must"],
    "must": ["mussed"],
    "mustard": ["mustered"],
    "mustered": ["mustard"],
    "naval": ["navel"],
    "navel": ["naval"],
    "nay": ["neigh"],
    "neigh": ["nay"],
    "Nice": ["niece"],
    "niece": ["Nice"],
    "none": ["nun"],
    "nun": ["none"],
    "oar": ["or", "ore"],
    "or": ["oar", "ore"],
    "ore": ["oar", "or"],
    "ode": ["owed"],
    "owed": ["ode"],
    "oh": ["owe"],
    "owe": ["oh"],
    "one": ["won"],
    "won": ["one"],
    "outcast": ["outcaste"],
    "outcaste": ["outcast"],
    "overdo": ["overdue"],
    "overdue": ["overdo"],
    "overseas": ["oversees"],
    "oversees": ["overseas"],
    "paced": ["paste"],
    "paste": ["paced"],
    "packed": ["pact"],
    "pact": ["packed"],
    "padded": ["patted"],
    "patted": ["padded"],
    "paean": ["paeon", "peon"],
    "paeon": ["paean", "peon"],
    "peon": ["paean", "paeon"],
    "pail": ["pale"],
    "pale": ["pail"],
    "pain": ["pane"],
    "pane": ["pain"],
    "pair": ["pare", "pear"],
    "pare": ["pair", "pear"],
    "pear": ["pair", "pare"],
    "palate": ["palette", "pallet"],
    "palette": ["palate", "pallet"],
    "pallet": ["palate", "palette"],
    "pall": ["Paul"],
    "Paul": ["pall"],
    "parish": ["perish"],
    "perish": ["parish"],
    "parlay": ["parley"],
    "parley": ["parlay"],
    "passed": ["past"],
    "past": ["passed"],
    "patience": ["patients"],
    "patients": ["patience"],
    "pause": ["paws"],
    "paws": ["pause"],
    "pea": ["pee"],
    "pee": ["pea"],
    "peace": ["piece"],
    "piece": ["peace"],
    "peak": ["peek", "pique"],
    "peek": ["peak", "pique"],
    "pique": ["peak", "peek"],
    "peal": ["peel"],
    "peel": ["peal"],
    "pearl": ["purl"],
    "purl": ["pearl"],
    "peas": ["pees"],
    "pees": ["peas"],
    "peat": ["Pete"],
    "Pete": ["peat"],
    "pedal": ["peddle", "petal"],
    "peddle": ["pedal", "petal"],
    "petal": ["pedal", "peddle"],
    "peer": ["pier"],
    "pier": ["peer"],
    "pekoe": ["picot"],
    "picot": ["pekoe"],
    "penance": ["pennants"],
    "pennants": ["penance"],
    "per": ["purr"],
    "purr": ["per"],
    "pervade": ["purveyed"],
    "purveyed": ["pervade"],
    "petrel": ["petrol"],
    "petrol": ["petrel"],
    "pi": ["pie"],
    "pie": ["pi"],
    "pidgin": ["pigeon"],
    "pigeon": ["pidgin"],
    "plain": ["plane"],
    "plane": ["plain"],
    "plait": ["plate"],
    "plate": ["plait"],
    "pleas": ["please"],
    "please": ["pleas"],
    "plum": ["plumb"],
    "plumb": ["plum"],
    "pole": ["poll"],
    "poll": ["pole"],
    "pore": ["pour"],
    "pour": ["pore"],
    "praise": ["prays", "preys"],
    "prays": ["praise", "preys"],
    "preys": ["praise", "prays"],
    "pray": ["prey"],
    "prey": ["pray"],
    "precedence": ["precedents"],
    "precedents": ["precedence"],
    "premier": ["premiere"],
    "premiere": ["premier"],
    "presence": ["presents"],
    "presents": ["presence"],
    "pride": ["pried"],
    "pried": ["pride"],
    "primer": ["primmer"],
    "primmer": ["primer"],
    "prince": ["prints"],
    "prints": ["prince"],
    "principal": ["principle"],
    "principle": ["principal"],
    "profit": ["prophet"],
    "prophet": ["profit"],
    "pros": ["prose"],
    "prose": ["pros"],
    "pugh": ["pew"],
    "pew": ["pugh"],
    "quarts": ["quartz"],
    "quartz": ["quarts"],
    "quince": ["quints"],
    "quints": ["quince"],
    "rabbet": ["rabbit"],
    "rabbit": ["rabbet"],
    "rack": ["wrack"],
    "wrack": ["rack"],
    "rain": ["reign", "rein"],
    "reign": ["rain", "rein"],
    "rein": ["rain", "reign"],
    "raise": ["rays", "raze"],
    "rays": ["raise", "raze"],
    "raze": ["raise", "rays"],
    "rap": ["wrap"],
    "wrap": ["rap"],
    "rapped": ["rapt", "wrapped"],
    "rapt": ["rapped", "wrapped"],
    "wrapped": ["rapped", "rapt"],
    "rapper": ["wrapper"],
    "wrapper": ["rapper"],
    "read": ["red", "reed"],
    "red": ["read"],
    "reed": ["read"],
    "real": ["reel"],
    "reel": ["real"],
    "reek": ["wreak"],
    "wreak": ["reek"],
    "residence": ["residents"],
    "residents": ["residence"],
    "rest": ["wrest"],
    "wrest": ["rest"],
    "retch": ["wretch"],
    "wretch": ["retch"],
    "review": ["revue"],
    "revue": ["review"],
    "rheum": ["room"],
    "room": ["rheum"],
    "rigger": ["rigor"],
    "rigor": ["rigger"],
    "right": ["rite", "write"],
    "rite": ["right", "write"],
    "write": ["right", "rite"],
    "ring": ["wring"],
    "wring": ["ring"],
    "road": ["rode", "rowed"],
    "rode": ["road", "rowed"],
    "rowed": ["road", "rode"],
    "roam": ["Rome"],
    "Rome": ["roam"],
    "roe": ["row"],
    "row": ["roe"],
    "role": ["roll"],
    "roll": ["role"],
    "rose": ["rows"],
    "rows": ["rose", "rouse"],
    "rote": ["wrote"],
    "wrote": ["rote"],
    "rough": ["ruff"],
    "ruff": ["rough"],
    "route": ["root"],
    "root": ["route"],
    "roux": ["rue"],
    "rue": ["roux", "rued"],
    "rude": ["rued"],
    "rued": ["rude", "rue"],
    "Russell": ["rustle"],
    "rustle": ["Russell"],
    "rye": ["wry"],
    "wry": ["rye"],
    "sac": ["sack"],
    "sack": ["sac"],
    "sachet": ["sashay"],
    "sashay": ["sachet"],
    "sacks": ["sax"],
    "sax": ["sacks"],
    "sail": ["sale"],
    "sale": ["sail"],
    "sane": ["seine"],
    "seine": ["sane"],
    "sari": ["sorry"],
    "sorry": ["sari"],
    "saver": ["savor"],
    "savor": ["saver"],
    "scene": ["seen"],
    "seen": ["scene"],
    "scull": ["skull"],
    "skull": ["scull"],
    "sea": ["see"],
    "see": ["sea"],
    "seam": ["seem"],
    "seem": ["seam"],
    "sear": ["seer", "sere"],
    "seer": ["sear", "sere"],
    "sere": ["sear", "seer"],
    "seas": ["sees", "seize"],
    "sees": ["seas", "seize"],
    "seize": ["seas", "sees"],
    "serf": ["surf"],
    "surf": ["serf"],
    "serge": ["surge"],
    "surge": ["serge"],
    "sew": ["so", "sow"],
    "so": ["sew", "sow"],
    "sow": ["sew", "so"],
    "shear": ["sheer"],
    "sheer": ["shear"],
    "shoe": ["shoo"],
    "shoo": ["shoe"],
    "shone": ["shown"],
    "shown": ["shone"],
    "sic": ["sick"],
    "sick": ["sic"],
    "side": ["sighed"],
    "sighed": ["side"],
    "sighs": ["size"],
    "size": ["sighs"],
    "sink": ["sync"],
    "sync": ["sink"],
    "Sioux": ["sue"],
    "sue": ["Sioux"],
    "slay": ["sleigh"],
    "sleigh": ["slay"],
    "sleight": ["slight"],
    "slight": ["sleight"],
    "slew": ["slue", "slough"],
    "slue": ["slew", "slough"],
    "slough": ["slew", "slue"],
    "sloe": ["slow"],
    "slow": ["sloe"],
    "soar": ["sore"],
    "sore": ["soar"],
    "soared": ["sword"],
    "sword": ["soared"],
    "sold": ["soled"],
    "soled": ["sold"],
    "sole": ["soul"],
    "soul": ["sole"],
    "some": ["sum"],
    "sum": ["some"],
    "son": ["sun"],
    "sun": ["son"],
    "soot": ["suit"],
    "suit": ["soot"],
    "spa": ["spay"],
    "spay": ["spa"],
    "stair": ["stare"],
    "stare": ["stair"],
    "stake": ["steak"],
    "steak": ["stake"],
    "staid": ["stayed"],
    "stayed": ["staid"],
    "stationary": ["stationery"],
    "stationery": ["stationary"],
    "steal": ["steel"],
    "steel": ["steal"],
    "step": ["steppe"],
    "steppe": ["step"],
    "stile": ["style"],
    "style": ["stile"],
    "straight": ["strait"],
    "strait": ["straight"],
    "straightened": ["straitened"],
    "straitened": ["straightened"],
    "suite": ["sweet"],
    "sweet": ["suite"],
    "tacked": ["tact"],
    "tacks": ["tax"],
    "tact": ["tacked"],
    "tail": ["tale"],
    "tale": ["tail"],
    "taper": ["tapir"],
    "tapir": ["taper"],
    "tarry": ["terry"],
    "terry": ["tarry"],
    "taught": ["taut"],
    "taut": ["taught"],
    "taupe": ["tope"],
    "tope": ["taupe"],
    "tax": ["tacks"],
    "tea": ["tee"],
    "tee": ["tea"],
    "team": ["teem"],
    "teem": ["team"],
    "tear": ["tier"],
    "tier": ["tear"],
    "teas": ["tease", "tees"],
    "tease": ["teas", "tees"],
    "tees": ["teas", "tease"],
    "tends": ["tens"],
    "tens": ["tends"],
    "tense": ["tents"],
    "tents": ["tense"],
    "tern": ["turn"],
    "turn": ["tern"],
    "Thai": ["tie"],
    "tie": ["Thai"],
    "the": ["thee"],
    "thee": ["the"],
    "their": ["there", "they’re"],
    "there": ["their", "they’re"],
    "they’re": ["their", "there"],
    "theirs": ["there’s"],
    "there’s": ["theirs"],
    "threw": ["through"],
    "through": ["threw"],
    "throes": ["throws"],
    "throws": ["throes"],
    "throne": ["thrown"],
    "thrown": ["throne"],
    "thyme": ["time"],
    "time": ["thyme"],
    "tic": ["tick"],
    "tick": ["tic"],
    "tide": ["tied"],
    "tied": ["tide"],
    "tigress": ["Tigris"],
    "Tigris": ["tigress"],
    "timber": ["timbre"],
    "timbre": ["timber"],
    "to": ["too", "two"],
    "too": ["to", "two"],
    "two": ["to", "too"],
    "toad": ["toed", "towed"],
    "toed": ["toad", "towed"],
    "towed": ["toad", "toed"],
    "toe": ["tow"],
    "tow": ["toe"],
    "told": ["tolled"],
    "tolled": ["told"],
    "tool": ["tulle"],
    "tulle": ["tool"],
    "tooter": ["Tudor", "tutor"],
    "Tudor": ["tooter", "tutor"],
    "tutor": ["tooter", "Tudor"],
    "tort": ["torte"],
    "torte": ["tort"],
    "tortuous": ["torturous"],
    "torturous": ["tortuous"],
    "tracked": ["tract"],
    "tract": ["tracked"],
    "trader": ["traitor"],
    "traitor": ["trader"],
    "troop": ["troupe"],
    "troupe": ["troop"],
    "trussed": ["trust"],
    "trust": ["trussed"],
    "tucks": ["tux"],
    "tux": ["tucks"],
    "turban": ["turbine"],
    "turbine": ["turban"],
    "udder": ["utter"],
    "utter": ["udder"],
    "undo": ["undue"],
    "undue": ["undo"],
    "vain": ["vane", "vein"],
    "vane": ["vain", "vein"],
    "vein": ["vain", "vane"],
    "valance": ["valence"],
    "valence": ["valance"],
    "vale": ["veil"],
    "veil": ["vale"],
    "venous": ["Venus"],
    "Venus": ["venous"],
    "verses": ["versus"],
    "versus": ["verses"],
    "very": ["vary"],
    "vary": ["very"],
    "vial": ["vile"],
    "vile": ["vial"],
    "vice": ["vise"],
    "vise": ["vice"],
    "wade": ["weighed"],
    "weighed": ["wade"],
    "wader": ["waiter"],
    "waiter": ["wader"],
    "wail": ["whale", "wale"],
    "whale": ["wail", "wale"],
    "wale": ["wail", "whale"],
    "wails": ["Wales", "whales"],
    "Wales": ["wails", "whales"],
    "whales": ["wails", "Wales"],
    "wain": ["wane", "Wayne"],
    "wane": ["wain", "Wayne"],
    "Wayne": ["wain", "wane"],
    "waist": ["waste"],
    "waste": ["waist"],
    "wait": ["weight"],
    "weight": ["wait"],
    "waiver": ["waver"],
    "waver": ["waiver"],
    "waive": ["wave"],
    "wave": ["waive"],
    "wax": ["whacks"],
    "whacks": ["wax"],
    "way": ["weigh", "whey"],
    "weigh": ["way", "whey"],
    "whey": ["way", "weigh"],
    "wains": ["wanes"],
    "wanes": ["wains"],
    "we": ["wee"],
    "wee": ["we"],
    "we'll": ["wheel"],
    "wheel": ["we'll"],
    "weak": ["week"],
    "week": ["weak"],
    "wear": ["where", "ware"],
    "where": ["wear", "ware"],
    "ware": ["wear", "where"],
    "wears": ["wares", "where’s"],
    "wares": ["wears", "where’s"],
    "where’s": ["wears", "wares"],
    "weather": ["whether", "wether"],
    "whether": ["weather", "wether"],
    "wether": ["weather", "whether"],
    "weave": ["we’ve"],
    "we’ve": ["weave"],
    "we'd": ["weed"],
    "weed": ["we'd"],
    "wet": ["whet"],
    "whet": ["wet"],
    "which": ["witch"],
    "witch": ["which"],
    "while": ["wile"],
    "wile": ["while"],
    "whine": ["wine"],
    "wine": ["whine"],
    "whined": ["wind", "wined"],
    "wind": ["whined", "wined"],
    "wined": ["whined", "wind"],
    "whir": ["were"],
    "were": ["whir"],
    "whirled": ["whorled", "world"],
    "whorled": ["whirled", "world"],
    "world": ["whirled", "whorled"],
    "whirred": ["word"],
    "word": ["whirred"],
    "whoa": ["woe"],
    "woe": ["whoa"],
    "wok": ["walk"],
    "walk": ["wok"],
    "wont": ["want"],
    "want": ["wont"],
    "wood": ["would"],
    "would": ["wood"],
    "wore": ["war"],
    "war": ["wore"],
    "warn": ["worn"],
    "worn": ["warn"],
    "wrung": ["rung"],
    "rung": ["wrung"],
    "yoke": ["yolk"],
    "yolk": ["yoke"],
    "yore": ["your", "you’re"],
    "your": ["yore", "you’re"],
    "you’re": ["yore", "your"],
    "you’ll": ["Yule"],
    "Yule": ["you’ll"]
};

function createHomophonesStore() {
  const { subscribe, set, update } = writable<Homophones>(homophonesData);

  return {
    subscribe,
    getHomophones: (word: string) => homophonesData[word.toLowerCase()] || [],
  };
}

export const homophonesStore = createHomophonesStore();
